apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock-server
spec:
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
      annotations:
        deployed-by: wiremock-operator
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
        - name: mocks-file
          configMap:
            name: json-mappings

      containers:
        - name: wiremock-server
          image: "quay.io/zgrinber/wiremock:latest"
          command: [ "bash" , "-c" ,"java -jar /var/wiremock/lib/wiremock-jre8-standalone.jar --port '$LISTENING_PORT'"]
          env:
            - name: LISTENING_PORT
              value: "9999"
          volumeMounts:
            - mountPath: /tmp/mocks
              name: mocks-file
          ports:
            - containerPort: 9999
              name: http

#          lifecycle:
#            postStart:
#              exec:
#                command: [ "/bin/sh","-c", " sleep 1 ; curl -X POST http://localhost:9999/__admin/mappings/import -T /tmp/mocks/mappings.json" ]